### 05. (실습)
PATCH http://localhost:3000/me?password=1234
###
PATCH http://localhost:3000/me?password=123456

### 07. (실습)
GET http://localhost:3000/products/1
###
GET http://localhost:3000/products/1/reviews
###
GET http://localhost:3000/products/2/reviews
###
GET http://localhost:3000/products/3/reviews